language: csharp
before_install:
 - sudo apt-get install -y libpango1.0-dev
addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - cmake
script:
 - ./build.sh --target=LinuxDaily
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
        branch: master
    local-dir: packaging/packages
    repo: Librelancer/daily-builds
