language: csharp
before_install:
 - sudo apt-get install -y libpango1.0-dev
script:
 - ./build.sh --target=LinuxDaily
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
        branch: master
    local-dir: packaging/packages
    repo: Librelancer/daily-builds
