language: csharp
addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - cmake
script:
 - ./build.sh --target=LinuxDaily
deploy:
    edge:
        branch: v1.8.47
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
        branch: master
    local-dir: packaging/packages
    repo: Librelancer/daily-builds
